title: "Zihao Chen"
email: "zihaochen17@fudan.edu.cn"
description: "我的学术研究和项目展示"
baseurl: "/"
url: "https://zhchenfdu.github.io" # 使用你自己的 GitHub Pages URL
theme: jekyll-theme-cayman
social_links:
  - name: "GitHub"
    url: "https://github.com/zhchenfdu"
  - name: "LinkedIn"
    url: "https://www.linkedin.com/in/yourprofile/"
  - name: "Twitter"
    url: "https://twitter.com/yourprofile"
